name: Custom Build And Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  # Build job
  builddeploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
          
       #Now because our URL's are programmed relative to the root URL, yet GitHub posts our code
       #at ROOT/REPO/, we need to replace all our links I can remember to think of with the prefixed REPO
      - name: 'Modify all Image src="/ File Paths'
        run: |
          find 'dist/' -type f -exec sed -i 's#src=\"\/#src=\"\/Portfolio\/#g' {} +
      - name: 'Modify all Hyperlink href="/ File Paths'
        run: |
          find 'dist/' -type f -exec sed -i 's#href=\"\/#href=\"\/Portfolio\/#g' {} +
      - name: 'Modify Some Other JS Component File Paths'
        run: |
          find 'dist/' -type f -exec sed -i 's#: \"\/#: \"\/Portfolio\/#g' {} +
          
      - name: Generate Folder For Tar
        run: 'mkdir -p dist/artifact'
      - name: Tar Files For Artifact
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "dist/" \
            -cvf "dist/artifact/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'github-pages'
          path: 'dist/artifact/'
          if-no-files-found: 'error'
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
        with:
          token: ${{ github.token }}
          artifact_name: 'github-pages'
